gjordde ändringar på min sida
axAlbers/Group-demo pull request #9
Opened 2023-09-05 13:46 UTC by okan98

2023-09-06 10:46 UTC, Deychen requested changes
What the hell is this?!

2023-09-06 10:46 UTC, axAlbers requested changes
Detta ser väldigt halvt ut. Bättre kan du.

2023-09-06 10:53 UTC, okan98 commented
nej komigen bara allow it man....

2023-09-07 07:49 UTC, axAlbers approved these changes
Fine i will accept

2023-09-11 10:28 UTC, axAlbers approved these changes

2023-09-11 10:28 UTC, merged